version: '3.8'

services:
  gerenciamento:
    build: ./Gerenciamento        
    container_name: Gerenciamento-svc
    ports:
      - "8081:8080"               
    volumes:
      - ./Gerenciamento/database.db:/app/database.db  
    networks:
      - escola-net

  atividades:
    build: ./Atividades
    container_name: Atividades-svc
    ports:
      - "8082:8080"               
    volumes:
      - ./Atividades/database.db:/app/database.db
    networks:
      - escola-net
    depends_on:
      - gerenciamento

  reservas:
    build: ./Reservas
    container_name: Reservas-svc
    ports:
      - "8083:8080"               
    volumes:
      - ./Reservas/database.db:/app/database.db
    networks:
      - escola-net
    depends_on:                   
      - gerenciamento
      
networks:
  escola-net:
    driver: bridge